### ISSUE TITLE
Gees 0.3.0 "Invocation of constructor threw an exception"

### ISSUE THREAD

**Issue by samcan** [scelts/msfslandingrate#6]
Hi, I just downloaded Gees 0.3.0, and am getting this error when attempting to open the program:

"The invocation of the constructor on type 'GeesWPF.MainWindow' that matches the specified binding constraints threw an exception."

I'm on Windows 10 v2004 x64.

Here's the contents of the log.txt file:

```10/13/2020 12:50:23 PM
0.3.0
The invocation of the constructor on type 'GeesWPF.MainWindow' that matches the specified binding constraints threw an exception.
PresentationFramework
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

10/13/2020 12:50:32 PM
0.3.0
The invocation of the constructor on type 'GeesWPF.MainWindow' that matches the specified binding constraints threw an exception.
PresentationFramework
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)```

**Comment by scelts** [comment]
Yep, issuing a hotfix 0.3.1 as we speek. Sorry for this!

**Comment by samcan** [comment]
No problem!

**Comment by scelts** [comment]
It was a problem with creating a flight log - wasn't already created when the app starts new and it attempted to read it.
